apiVersion: v1
kind: Service
metadata:
  name: volodymyr-app-service
spec:
  selector:
    app: volodymyr-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
